#!/bin/bash

# CFD Project Help Script
# Shows available commands and usage

echo "🌊 CFD Unsteady Vortex Simulation - Available Commands"
echo "======================================================"
echo ""
echo "📋 QUICK COMMANDS:"
echo "  ./quick_animate.sh           - Create animated GIF from existing data"
echo "  ./quick_view.sh [frame]      - View specific frame (default: frame 5)"
echo "  ./run_cfd_with_matplotlib.sh - Full workflow: build + simulate + visualize"
echo ""
echo "🔧 MANUAL COMMANDS (requires virtual environment):"
echo "  source cfd_venv/bin/activate"
echo "  python matplotlib_cfd_viewer.py --animate --fps 4"
echo "  python matplotlib_cfd_viewer.py --frame 0"
echo "  python matplotlib_cfd_viewer.py --save-frames"
echo ""
echo "📁 OUTPUT LOCATIONS:"
echo "  VTK files:     output/unsteady_vortex/*.vtk"
echo "  Animation:     output/unsteady_vortex/cfd_animation.gif"
echo "  Frame images:  output/unsteady_vortex/frame_images/*.png"
echo ""
echo "🚀 TYPICAL WORKFLOW:"
echo "  1. Run simulation:     ./run_cfd_with_matplotlib.sh"
echo "  2. View animation:     ./quick_animate.sh"
echo "  3. View specific frame: ./quick_view.sh 3"
echo ""
echo "💡 TIPS:"
echo "  - Animation opens automatically in your default image viewer"
echo "  - Frame viewer shows interactive matplotlib plot"
echo "  - All scripts handle virtual environment activation automatically"
echo ""
